// apps/web/src/pages/DashboardPage.tsx
import { useEffect, useState } from 'react';
import { useHistory } from 'react-router-dom';
import {
  IonBadge,
  IonButton,
  IonCard,
  IonCardContent,
  IonSpinner,
} from '@ionic/react';
import type { IconType } from 'react-icons';
import {
  LuActivity,
  LuBoxes,
  LuContact,
  LuCpu,
  LuFileText,
  LuGauge,
  LuLayoutGrid,
  LuPlus,
  LuReceipt,
  LuScanLine,
  LuTrendingDown,
  LuTrendingUp,
  LuTriangleAlert,
  LuUsers,
} from 'react-icons/lu';
import { PageScaffold } from '@erplora/dashboard-shell';
import { PagePanel } from '../components/PagePanel';
import { PageTabBar, type PageTabBarItem } from '../components/PageTabBar';
import { loadMenu, type MenuEntry } from '../module-loader';

type Tab = 'resumen' | 'apps' | 'actividad';

const tabs: Array<PageTabBarItem<Tab>> = [
  { value: 'resumen', label: 'Resumen', icon: <LuGauge size={22} /> },
  { value: 'apps', label: 'Aplicaciones', icon: <LuLayoutGrid size={22} /> },
  { value: 'actividad', label: 'Actividad', icon: <LuActivity size={22} /> },
];

// KPIs de cabecera. Demo por ahora; en producción vendrán del runtime / módulos.
interface Kpi {
  label: string;
  value: string;
  Icon: IconType;
  sub?: string;
  trend?: 'up' | 'down';
}

const KPIS: Kpi[] = [
  { label: 'Ventas hoy', value: '€4 812', Icon: LuTrendingUp, sub: '+12,4% vs ayer', trend: 'up' },
  { label: 'Pedidos', value: '183', Icon: LuReceipt, sub: '+9 en la última hora', trend: 'up' },
  { label: 'Personal activo', value: '6', Icon: LuUsers, sub: '2 en caja ahora' },
  { label: 'Stock bajo', value: '7', Icon: LuTriangleAlert, sub: 'bajo umbral', trend: 'down' },
];

// Mapa icono por clave de nav del módulo (react-icons, homogéneo con el resto del shell).
const MODULE_ICONS: Record<string, IconType> = {
  pos: LuScanLine,
  cash: LuScanLine,
  people: LuUsers,
  customers: LuContact,
  invoice: LuFileText,
  document: LuFileText,
  cube: LuBoxes,
};

function moduleIcon(entry: MenuEntry): IconType {
  return MODULE_ICONS[entry.nav.icon ?? ''] ?? LuBoxes;
}

interface FeedItem {
  primary: string;
  sub: string;
  tone: 'success' | 'warning' | 'primary';
}

const FEED: FeedItem[] = [
  { primary: 'Pedido #1042 cerrado', sub: '38,90 € · tarjeta · caja 1', tone: 'success' },
  { primary: 'Alerta de stock · Cola 33cl', sub: 'bajo umbral (quedan 4)', tone: 'warning' },
  { primary: 'Lucía García fichó entrada', sub: 'caja 2', tone: 'primary' },
  { primary: 'Factura INV-2026-00018 pagada', sub: '29,99 €', tone: 'success' },
];

export function DashboardPage() {
  const history = useHistory();
  const [tab, setTab] = useState<Tab>('resumen');
  const [modules, setModules] = useState<MenuEntry[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let cancelled = false;
    loadMenu()
      .then((entries) => {
        if (!cancelled) setModules(entries);
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, []);

  return (
    <PageScaffold title="Dashboard" footer={<PageTabBar value={tab} items={tabs} onChange={setTab} />}>
      {tab === 'resumen' && (
        <PagePanel>
          {/* KPIs */}
          <div className="erplora-kpi-grid">
            {KPIS.map((k) => (
              <IonCard key={k.label} className="settings-card ion-no-margin">
                <IonCardContent>
                  <div className="erplora-kpi">
                    <div className="erplora-kpi__top">
                      <span className="erplora-kpi__label">{k.label}</span>
                      <span className="erplora-kpi-icon">
                        <k.Icon size={20} />
                      </span>
                    </div>
                    <span className="erplora-kpi__value">{k.value}</span>
                    {k.sub && (
                      <span className={`erplora-kpi__sub${k.trend ? ` is-${k.trend}` : ''}`}>
                        {k.trend === 'up' && <LuTrendingUp size={14} />}
                        {k.trend === 'down' && <LuTrendingDown size={14} />}
                        {k.sub}
                      </span>
                    )}
                  </div>
                </IonCardContent>
              </IonCard>
            ))}
          </div>

          {/* Estado del terminal */}
          <IonCard className="settings-card ion-no-margin">
            <IonCardContent>
              <h2 className="erplora-card-title">Este terminal</h2>
              <dl className="erplora-kv">
                <dt>Plan</dt>
                <dd className="erplora-mono">Starter</dd>
                <dt>Estado</dt>
                <dd>
                  <IonBadge color="success">Activo</IonBadge>
                </dd>
                <dt>Próxima factura</dt>
                <dd className="erplora-mono">13 jun 2026</dd>
                <dt>Bridge</dt>
                <dd>
                  <IonBadge color="medium">Desconectado</IonBadge>
                </dd>
              </dl>
              <IonButton expand="block" fill="outline" onClick={() => history.push('/system')}>
                <LuCpu size={18} style={{ marginRight: 8 }} /> Abrir sistema
              </IonButton>
            </IonCardContent>
          </IonCard>
        </PagePanel>
      )}

      {tab === 'apps' && (
        <PagePanel>
          {loading ? (
            <div className="flex items-center gap-2 py-6 text-[color:var(--ion-color-medium)]">
              <IonSpinner name="crescent" /> Cargando módulos…
            </div>
          ) : (
            <div className="erplora-tile-grid">
              {modules.map((entry) => {
                const Icon = moduleIcon(entry);
                return (
                  <IonCard
                    key={`${entry.moduleId}:${entry.nav.id}`}
                    button
                    className="settings-card ion-no-margin"
                    onClick={() => history.push(`/m/${entry.moduleId}`)}
                  >
                    <IonCardContent className="flex min-h-28 flex-col items-center justify-center gap-3 text-center">
                      <span className="erplora-kpi-icon">
                        <Icon size={22} />
                      </span>
                      <strong>{entry.nav.label}</strong>
                    </IonCardContent>
                  </IonCard>
                );
              })}
              <IonCard
                button
                className="settings-card ion-no-margin"
                onClick={() => history.push('/marketplace')}
              >
                <IonCardContent className="flex min-h-28 flex-col items-center justify-center gap-3 text-center">
                  <span className="erplora-kpi-icon">
                    <LuPlus size={22} />
                  </span>
                  <strong>Añadir módulo</strong>
                </IonCardContent>
              </IonCard>
            </div>
          )}
        </PagePanel>
      )}

      {tab === 'actividad' && (
        <PagePanel>
          <h2 className="erplora-card-title">Actividad reciente</h2>
          <ul className="erplora-feed">
            {FEED.map((f) => (
              <li key={f.primary}>
                <span className={`erplora-feed__dot is-${f.tone}`} />
                <div>
                  <div className="erplora-feed__primary">{f.primary}</div>
                  <div className="erplora-feed__sub">{f.sub}</div>
                </div>
              </li>
            ))}
          </ul>
        </PagePanel>
      )}
    </PageScaffold>
  );
}

// apps/web/src/views/DashboardPage.vue
<template>
  <AppPage :title="t('nav.home')">
      <!-- ── Resumen ── -->
      <template v-if="tab === 'resumen'">
        <ion-grid class="ion-no-padding">
          <ion-row>
            <ion-col v-for="kpi in KPIS" :key="kpi.label" size="6" size-md="3">
              <ion-card class="ion-no-margin">
                <ion-card-header>
                  <ion-card-subtitle>
                    <HubIcon :name="kpi.icon" /> {{ kpi.label }}
                  </ion-card-subtitle>
                  <ion-card-title>{{ kpi.value }}</ion-card-title>
                </ion-card-header>
                <ion-card-content v-if="kpi.sub">
                  <ion-text :color="trendColor(kpi.trend)">
                    <HubIcon v-if="kpi.trend === 'up'" name="trending-up-outline" />
                    <HubIcon v-else-if="kpi.trend === 'down'" name="trending-down-outline" />
                    {{ kpi.sub }}
                  </ion-text>
                </ion-card-content>
              </ion-card>
            </ion-col>
          </ion-row>
        </ion-grid>

        <ion-list inset>
          <ion-list-header>Este terminal</ion-list-header>
          <ion-item>
            <ion-label>Plan</ion-label>
            <ion-note slot="end">Starter</ion-note>
          </ion-item>
          <ion-item>
            <ion-label>Estado</ion-label>
            <ion-badge slot="end" color="success">Activo</ion-badge>
          </ion-item>
          <ion-item>
            <ion-label>Próxima factura</ion-label>
            <ion-note slot="end">13 jun 2026</ion-note>
          </ion-item>
          <ion-item lines="none">
            <ion-label>Bridge</ion-label>
            <ion-badge slot="end" color="medium">Desconectado</ion-badge>
          </ion-item>
        </ion-list>
        <ion-button expand="block" fill="outline" router-link="/system" router-direction="forward">
          <HubIcon name="hardware-chip-outline" slot="start" /> Abrir sistema
        </ion-button>
      </template>

      <!-- ── Aplicaciones ── -->
      <template v-else-if="tab === 'apps'">
        <ion-list v-if="loading" inset>
          <ion-item lines="none">
            <ion-spinner slot="start" name="crescent" />
            <ion-label>Cargando módulos…</ion-label>
          </ion-item>
        </ion-list>
        <ion-grid v-else class="ion-no-padding">
          <ion-row>
            <ion-col v-for="entry in modules" :key="entry.moduleId" size="6" size-md="3">
              <ion-card button class="ion-no-margin ion-text-center" @click="router.push(`/m/${entry.moduleId}`)">
                <ion-card-content>
                  <HubIcon :name="entry.iconSvg ?? entry.nav.icon" size="large" />
                  <p>{{ entry.moduleName }}</p>
                </ion-card-content>
              </ion-card>
            </ion-col>
            <ion-col size="6" size-md="3">
              <ion-card button class="ion-no-margin ion-text-center" router-link="/marketplace" router-direction="forward">
                <ion-card-content>
                  <HubIcon name="add-outline" size="large" />
                  <p>Añadir módulo</p>
                </ion-card-content>
              </ion-card>
            </ion-col>
          </ion-row>
        </ion-grid>
      </template>

      <!-- ── Actividad ── -->
      <template v-else-if="tab === 'actividad'">
        <ion-list inset>
          <ion-list-header>Actividad reciente</ion-list-header>
          <ion-item v-for="item in FEED" :key="item.primary" :lines="item === FEED[FEED.length - 1] ? 'none' : 'inset'">
            <HubIcon slot="start" name="ellipse" :color="item.tone" class="feed-dot" />
            <ion-label>
              <h3>{{ item.primary }}</h3>
              <p>{{ item.sub }}</p>
            </ion-label>
          </ion-item>
        </ion-list>
      </template>
    <!-- Tabs en footer -->
    <template #footer>
      <ion-footer class="ion-no-border">
      <ion-toolbar>
        <ion-segment
          :value="tab"
          @ion-change="tab = ($event as CustomEvent<{ value: Tab }>).detail.value"
        >
          <ion-segment-button value="resumen">
            <HubIcon name="speedometer-outline" />
            <ion-label>Resumen</ion-label>
          </ion-segment-button>
          <ion-segment-button value="apps">
            <HubIcon name="grid-outline" />
            <ion-label>Aplicaciones</ion-label>
          </ion-segment-button>
          <ion-segment-button value="actividad">
            <HubIcon name="pulse-outline" />
            <ion-label>Actividad</ion-label>
          </ion-segment-button>
        </ion-segment>
      </ion-toolbar>
      </ion-footer>
    </template>
  </AppPage>
</template>

<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { useRouter } from 'vue-router';
import { useI18n } from 'vue-i18n';
import {
  IonFooter,
  IonSegment, IonSegmentButton, IonLabel, IonCard, IonCardHeader, IonCardTitle, IonCardSubtitle,
  IonCardContent, IonGrid, IonRow, IonCol,  IonBadge, IonButton, IonSpinner,
  IonList, IonListHeader, IonItem, IonNote, IonText, IonToolbar
} from '@ionic/vue';
import HubIcon from '../components/HubIcon.vue';
import AppPage from '../components/AppPage.vue';
import { loadMenu, type MenuEntry } from '../lib/module-loader';

const { t } = useI18n();

type Tab = 'resumen' | 'apps' | 'actividad';
type Trend = 'up' | 'down';
type Tone = 'success' | 'warning' | 'primary';

const tab = ref<Tab>('resumen');
const modules = ref<MenuEntry[]>([]);
const loading = ref<boolean>(true);
const router = useRouter();

const trendColor = (t?: Trend): string => (t === 'up' ? 'success' : t === 'down' ? 'danger' : 'medium');

interface Kpi { label: string; value: string; icon: string; sub?: string; trend?: Trend }
const KPIS: Kpi[] = [
  { label: 'Ventas hoy', value: '€4 812', icon: 'trending-up-outline', sub: '+12,4% vs ayer', trend: 'up' },
  { label: 'Pedidos', value: '183', icon: 'receipt-outline', sub: '+9 en la última hora', trend: 'up' },
  { label: 'Personal activo', value: '6', icon: 'people-outline', sub: '2 en caja ahora' },
  { label: 'Stock bajo', value: '7', icon: 'warning-outline', sub: 'bajo umbral', trend: 'down' },
];

interface FeedItem { primary: string; sub: string; tone: Tone }
const FEED: FeedItem[] = [
  { primary: 'Pedido #1042 cerrado', sub: '38,90 € · tarjeta · caja 1', tone: 'success' },
  { primary: 'Alerta de stock · Cola 33cl', sub: 'bajo umbral (quedan 4)', tone: 'warning' },
  { primary: 'Lucía García fichó entrada', sub: 'caja 2', tone: 'primary' },
  { primary: 'Factura INV-2026-00018 pagada', sub: '29,99 €', tone: 'success' },
];

onMounted(async () => {
  try {
    // Una tarjeta por MÓDULO (loadMenu devuelve una entrada por cada navigation[] del manifest).
    const entries = await loadMenu();
    const byModule = new Map<string, MenuEntry>();
    for (const e of entries) if (!byModule.has(e.moduleId)) byModule.set(e.moduleId, e);
    modules.value = [...byModule.values()];
  } finally {
    loading.value = false;
  }
});
</script>

<style scoped>
/* Único ajuste: el "punto" de actividad es un ion-icon pequeño. */
.feed-dot {
  font-size: 0.6rem;
}
</style>
