// apps/web/src/pages/auth/LoginPage.tsx
// Autenticación con Ionic + Tailwind + react-icons. Pasos (ARQUITECTURA.md §2.9):
//   - 'pin'   : dispositivo de confianza → elegir usuario + PIN
//   - 'email' : login email+password (online)
//   - 'setup' : crear PIN tras el 1er login (con confirmación)
//
// Si el dispositivo es de confianza, se muestran TABS (PIN | Email) para alternar.
// El acceso por PIN solo se habilita si se marcó "Confiar en este dispositivo" al entrar
// con email (un icono "i" lo explica junto al checkbox).
import { useState } from 'react';
import { useHistory } from 'react-router-dom';
import {
  IonPage, IonContent, IonCard, IonCardContent, IonInput, IonButton, IonCheckbox,
  IonText, IonSpinner, IonSegment, IonSegmentButton, IonLabel, IonPopover,
} from '@ionic/react';
import { LuSun, LuMoon, LuLogIn, LuKeyRound, LuMail, LuInfo } from 'react-icons/lu';
import { Logo } from '../../ui/Logo';
import { PinPad } from '../../ui/PinPad';
import { useAuth } from '../../lib/auth';
import { useTheme } from '../../lib/theme';
import { useToast } from '../../lib/toast';

type Step = 'pin' | 'email' | 'setup';

export function LoginPage() {
  const auth = useAuth();
  const { dark, toggle } = useTheme();
  const [step, setStep] = useState<Step>(auth.trusted ? 'pin' : 'email');

  // Las tabs solo tienen sentido si el dispositivo es de confianza (hay PIN disponible)
  // y no estamos en el alta de PIN (setup).
  const showTabs = auth.trusted && step !== 'setup';

  return (
    <IonPage>
      <IonContent>
        <IonButton fill="clear" aria-label="Tema" className="absolute right-2 top-2 z-10" onClick={toggle}>
          {dark ? <LuSun size={20} /> : <LuMoon size={20} />}
        </IonButton>

        <div className="grid min-h-full place-items-center px-4 py-10">
          <div className="w-full max-w-[400px]">
            <div className="mb-8 flex flex-col items-center gap-3 text-center">
              <Logo size="lg" />
              <IonText color="medium">
                <p className="text-[14px]">
                  {step === 'setup' ? 'Crea tu PIN de acceso' : step === 'pin' ? 'Introduce tu PIN' : 'Inicia sesión en tu hub'}
                </p>
              </IonText>
            </div>

            <IonCard className="ion-no-margin">
              <IonCardContent>
                {showTabs && (
                  <IonSegment
                    value={step}
                    onIonChange={(e) => setStep(e.detail.value as Step)}
                    className="mb-5"
                  >
                    <IonSegmentButton value="pin">
                      <LuKeyRound size={16} className="mr-1.5" />
                      <IonLabel>PIN</IonLabel>
                    </IonSegmentButton>
                    <IonSegmentButton value="email">
                      <LuMail size={16} className="mr-1.5" />
                      <IonLabel>Email</IonLabel>
                    </IonSegmentButton>
                  </IonSegment>
                )}

                {step === 'pin' && <PinLogin onUseEmail={() => setStep('email')} hideSwitch={showTabs} />}
                {step === 'email' && <EmailForm onFirstTime={() => setStep('setup')} canUsePin={auth.trusted} onUsePin={() => setStep('pin')} hideSwitch={showTabs} />}
                {step === 'setup' && <PinSetup />}
              </IonCardContent>
            </IonCard>

            <p className="mt-6 text-center text-[12px] text-[color:var(--ion-color-medium)]">
              ERPlora · {step === 'pin' ? 'dispositivo de confianza' : 'conexión segura con Cloud'}
            </p>
          </div>
        </div>
      </IonContent>
    </IonPage>
  );
}

function EmailForm({ onFirstTime, canUsePin, onUsePin, hideSwitch }: { onFirstTime: () => void; canUsePin: boolean; onUsePin: () => void; hideSwitch?: boolean }) {
  const auth = useAuth();
  const { toast } = useToast();
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [trust, setTrust] = useState(true);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  async function submit(e: React.FormEvent) {
    e.preventDefault();
    setError('');
    setLoading(true);
    try {
      const { firstTime } = await auth.loginEmail(email.trim().toLowerCase(), password, trust);
      if (firstTime && trust) onFirstTime(); // solo creamos PIN si el dispositivo es de confianza
      else toast('Sesión iniciada', { color: 'success' });
    } catch {
      setError('No se pudo iniciar sesión. Revisa tus credenciales o la conexión.');
    } finally {
      setLoading(false);
    }
  }

  return (
    <form onSubmit={submit} className="flex flex-col gap-3">
      <IonInput label="Email" labelPlacement="stacked" type="email" autocomplete="username" fill="outline" placeholder="tu@empresa.com" value={email} onIonInput={(e) => setEmail(e.detail.value ?? '')} />
      <IonInput label="Contraseña" labelPlacement="stacked" type="password" autocomplete="current-password" fill="outline" placeholder="••••••••" value={password} onIonInput={(e) => setPassword(e.detail.value ?? '')} />

      <div className="flex items-center gap-1.5">
        <IonCheckbox checked={trust} onIonChange={(e) => setTrust(e.detail.checked)} labelPlacement="end">
          <span className="text-[13.5px]">Confiar en este dispositivo</span>
        </IonCheckbox>
        <IonButton id="trust-info" fill="clear" size="small" aria-label="Más información sobre dispositivos de confianza" className="m-0 h-6">
          <LuInfo size={16} />
        </IonButton>
        <IonPopover trigger="trust-info" triggerAction="click" side="top" alignment="center">
          <div className="max-w-[260px] p-3 text-[13px] leading-snug">
            <p className="mb-1 font-semibold">Acceso por PIN</p>
            <p className="text-[color:var(--ion-color-medium)]">
              Marca esta casilla para poder entrar con un <strong>PIN</strong> en este dispositivo
              la próxima vez, sin escribir email y contraseña. Si no la marcas, siempre tendrás que
              iniciar sesión con email.
            </p>
          </div>
        </IonPopover>
      </div>

      {error && <IonText color="danger"><p className="text-[13px]">{error}</p></IonText>}
      <IonButton type="submit" expand="block" disabled={loading}>
        {loading ? <IonSpinner name="crescent" /> : <><LuLogIn size={18} className="mr-2" />Entrar</>}
      </IonButton>
      {canUsePin && !hideSwitch && <IonButton fill="clear" size="small" onClick={onUsePin}>Usar PIN en su lugar</IonButton>}
    </form>
  );
}

function PinLogin({ onUseEmail, hideSwitch }: { onUseEmail: () => void; hideSwitch?: boolean }) {
  const auth = useAuth();
  const { toast } = useToast();
  const users = auth.trustedUsers;
  // Con un solo usuario no hace falta elegir; con varios se muestran las cards primero.
  const [userId, setUserId] = useState<string | null>(users.length === 1 ? users[0].id : null);
  const [pin, setPin] = useState('');
  const [error, setError] = useState(false);

  async function onChange(next: string) {
    setError(false);
    setPin(next);
    if (next.length === 4 && userId) {
      try {
        await auth.loginPin(userId, next);
        toast('Bienvenido', { color: 'success' });
      } catch {
        setError(true);
        setPin('');
      }
    }
  }

  const current = users.find((u) => u.id === userId);

  // Paso 1 — elegir con qué usuario autenticarse (cards de todos los disponibles).
  if (!current) {
    return (
      <div className="flex flex-col gap-4">
        <IonText color="medium"><p className="text-center text-[14px]">Elige tu usuario</p></IonText>
        <div className="grid grid-cols-2 gap-3">
          {users.map((u) => (
            <button
              key={u.id}
              type="button"
              onClick={() => { setUserId(u.id); setPin(''); setError(false); }}
              className="flex flex-col items-center gap-2 rounded-xl border border-[color:var(--ion-color-step-150,#dcdcdc)] bg-[color:var(--ion-card-background,#fff)] p-4 text-center shadow-sm transition hover:-translate-y-0.5 hover:border-[color:var(--ion-color-primary)] hover:shadow-md active:scale-[.98]"
            >
              <span className="grid h-12 w-12 place-items-center rounded-full text-[16px] font-semibold text-[color:var(--ion-color-primary)]" style={{ background: 'rgba(20,150,214,.12)' }}>{u.initials}</span>
              <span className="min-w-0 max-w-full truncate text-[14px] font-semibold">{u.name}</span>
              {u.email && <span className="min-w-0 max-w-full truncate text-[11px] text-[color:var(--ion-color-medium)]">{u.email}</span>}
            </button>
          ))}
        </div>
        {!hideSwitch && <IonButton fill="clear" size="small" onClick={onUseEmail}>Iniciar sesión con email</IonButton>}
      </div>
    );
  }

  // Paso 2 — PIN del usuario elegido.
  return (
    <div className="flex flex-col items-center gap-5">
      <div className="text-center">
        <span className="grid mx-auto h-14 w-14 place-items-center rounded-full text-[18px] font-semibold text-[color:var(--ion-color-primary)]" style={{ background: 'rgba(20,150,214,.12)' }}>{current.initials}</span>
        <p className="mt-2 text-[14px] font-semibold">{current.name}</p>
        {users.length > 1 && (
          <button
            type="button"
            onClick={() => { setUserId(null); setPin(''); setError(false); }}
            className="mt-1 text-[12px] text-[color:var(--ion-color-primary)] hover:underline"
          >
            Cambiar usuario
          </button>
        )}
      </div>
      <PinPad value={pin} onChange={onChange} error={error} />
      {error && <IonText color="danger"><p className="text-[13px]">PIN incorrecto</p></IonText>}
      {!hideSwitch && <IonButton fill="clear" size="small" onClick={onUseEmail}>Iniciar sesión con email</IonButton>}
    </div>
  );
}

function PinSetup() {
  const auth = useAuth();
  const history = useHistory();
  const { toast } = useToast();
  const [first, setFirst] = useState('');
  const [confirm, setConfirm] = useState('');
  const [phase, setPhase] = useState<'first' | 'confirm'>('first');
  const [error, setError] = useState(false);

  async function onChange(next: string) {
    setError(false);
    if (phase === 'first') {
      setFirst(next);
      if (next.length === 4) setPhase('confirm');
    } else {
      setConfirm(next);
      if (next.length === 4) {
        if (next === first) {
          await auth.setupPin(next);
          toast('PIN creado', { color: 'success' });
          history.push('/');
        } else {
          setError(true);
          setFirst('');
          setConfirm('');
          setPhase('first');
        }
      }
    }
  }

  return (
    <div className="flex flex-col items-center gap-5">
      <IonText color="medium"><p className="text-[14px]">{phase === 'first' ? 'Elige un PIN de 4 dígitos' : 'Confirma tu PIN'}</p></IonText>
      <PinPad value={phase === 'first' ? first : confirm} onChange={onChange} error={error} />
      {error && <IonText color="danger"><p className="text-[13px]">Los PIN no coinciden, inténtalo de nuevo</p></IonText>}
    </div>
  );
}

// apps/web/src/views/LoginPage.vue
<template>
  <ion-page>
    <!-- Sin ion-header en login (no hay menú ni barra de título). -->
    <ion-content>

      <!-- Botón de tema: esquina superior derecha -->
      <ion-button
        fill="clear"
        aria-label="Cambiar tema"
        class="theme-btn"
        @click="toggleTheme"
      >
        <HubIcon slot="icon-only" :name="isDark ? 'sunny-outline' : 'moon-outline'" />
      </ion-button>

      <div class="login-wrap">
        <div class="login-box">

          <!-- Logo / cabecera -->
          <div class="logo-area">
            <!-- Logo de marca: el personalizado del hub si lo hay, si no el de ERPlora (local,
                offline-safe). Si la URL personalizada falla/está offline, cae al logo local. -->
            <img
              class="logo-img"
              :src="hubLogo"
              alt="ERPlora"
              decoding="async"
              @error="onLogoError"
            />
            <p class="logo-sub">
              <template v-if="step === 'setup'">Crea tu PIN de acceso</template>
              <template v-else-if="step === 'pin'">Introduce tu PIN</template>
              <template v-else>Inicia sesión en tu hub</template>
            </p>
          </div>

          <!-- Tarjeta principal -->
          <ion-card class="ion-no-margin login-card">
            <ion-card-content>

              <!-- Tabs PIN | Email (solo cuando el dispositivo es de confianza y no en setup) -->
              <ion-segment
                v-if="showTabs"
                :value="step"
                class="mb-5"
                @ion-change="step = ($event as CustomEvent<{ value: Step }>).detail.value"
              >
                <ion-segment-button value="pin">
                  <HubIcon name="keypad-outline" />
                  <ion-label>PIN</ion-label>
                </ion-segment-button>
                <ion-segment-button value="email">
                  <HubIcon name="mail-outline" />
                  <ion-label>Email</ion-label>
                </ion-segment-button>
              </ion-segment>

              <!-- Paso: login por email+contraseña -->
              <form v-if="step === 'email'" class="step-form" @submit.prevent="submitEmail">
                <ion-input
                  v-model="emailVal"
                  label="Email"
                  label-placement="stacked"
                  type="email"
                  autocomplete="username"
                  fill="outline"
                  placeholder="tu@empresa.com"
                  @ion-input="emailVal = ($event as CustomEvent<{ value: string }>).detail.value ?? ''"
                />
                <ion-input
                  v-model="passwordVal"
                  label="Contraseña"
                  label-placement="stacked"
                  type="password"
                  autocomplete="current-password"
                  fill="outline"
                  placeholder="••••••••"
                  @ion-input="passwordVal = ($event as CustomEvent<{ value: string }>).detail.value ?? ''"
                >
                  <ion-input-password-toggle slot="end"></ion-input-password-toggle>
                </ion-input>

                <!-- Checkbox "confiar en este dispositivo" + popover informativo -->
                <div class="trust-row">
                  <ion-checkbox
                    :checked="trust"
                    label-placement="end"
                    @ion-change="trust = ($event as CustomEvent<{ checked: boolean }>).detail.checked"
                  >
                    <span class="trust-label">Confiar en este dispositivo</span>
                  </ion-checkbox>
                  <ion-button
                    id="trust-info-btn"
                    fill="clear"
                    size="small"
                    aria-label="Más información sobre dispositivos de confianza"
                    class="trust-info-btn"
                  >
                    <HubIcon slot="icon-only" name="information-circle-outline" />
                  </ion-button>
                  <ion-popover
                    trigger="trust-info-btn"
                    trigger-action="click"
                    side="top"
                    alignment="center"
                  >
                    <div class="popover-content">
                      <p class="popover-title">Acceso por PIN</p>
                      <p class="popover-body">
                        Marca esta casilla para poder entrar con un <strong>PIN</strong> en este
                        dispositivo la próxima vez, sin escribir email y contraseña. Si no la marcas,
                        siempre tendrás que iniciar sesión con email.
                      </p>
                    </div>
                  </ion-popover>
                </div>

                <ion-note v-if="emailError" color="danger" class="error-note">
                  {{ emailError }}
                </ion-note>

                <ion-button type="submit" expand="block" :disabled="emailLoading">
                  <ion-spinner v-if="emailLoading" name="crescent" />
                  <template v-else>
                    <HubIcon slot="start" name="log-in-outline" />
                    Entrar
                  </template>
                </ion-button>

                <ion-button
                  v-if="trusted && !showTabs"
                  fill="clear"
                  size="small"
                  @click="step = 'pin'"
                >
                  Usar PIN en su lugar
                </ion-button>
              </form>

              <!-- Paso: login por PIN -->
              <div v-else-if="step === 'pin'" class="step-form">

                <!-- Paso 1: elegir usuario (cuando hay varios en el dispositivo) -->
                <template v-if="!pinUser">
                  <ion-text color="medium" class="pin-choose-title">
                    <p>Elige tu usuario</p>
                  </ion-text>
                  <div class="user-scroll">
                    <div class="user-grid">
                      <ion-card
                        v-for="u in trustedUsers"
                        :key="u.id"
                        button
                        class="user-card"
                        @click="selectPinUser(u)"
                      >
                        <ion-card-content class="ion-text-center">
                          <ok-avatar :name="u.name" size="lg"></ok-avatar>
                          <p class="user-name">{{ u.name }}</p>
                          <p v-if="u.email" class="user-email">{{ u.email }}</p>
                        </ion-card-content>
                      </ion-card>
                    </div>
                  </div>
                  <ion-button
                    v-if="!showTabs"
                    fill="clear"
                    size="small"
                    @click="step = 'email'"
                  >
                    Iniciar sesión con email
                  </ion-button>
                </template>

                <!-- Paso 2: introducir PIN del usuario elegido -->
                <template v-else>
                  <div class="pin-user-info">
                    <ok-avatar :name="pinUser.name" size="lg"></ok-avatar>
                    <p class="user-name mt-2">{{ pinUser.name }}</p>
                  </div>

                  <!-- ok-pinpad: pantalla (4 círculos), teclado y, si hay varios usuarios,
                       tecla «cambiar usuario» (flecha a la izquierda del 0; borrado a la derecha). -->
                  <div class="pinpad-wrap">
                    <ok-pinpad
                      ref="mainPinpadRef"
                      dots
                      :length="4"
                      :error="pinError"
                      secondary-icon="arrow-back-outline"
                      secondary-label="Cambiar usuario"
                      @ok-input="onMainPinInput"
                      @ok-complete="onMainPinComplete"
                      @ok-secondary="onChangeUser"
                    ></ok-pinpad>
                  </div>

                  <ion-note v-if="pinError" color="danger" class="error-note">
                    PIN incorrecto
                  </ion-note>
                  <ion-button
                    v-if="!showTabs"
                    fill="clear"
                    size="small"
                    @click="onPinToEmail"
                  >
                    Iniciar sesión con email
                  </ion-button>
                </template>
              </div>

              <!-- Paso: alta del PIN (primer login con "Confiar en este dispositivo") -->
              <div v-else-if="step === 'setup'" class="step-form">
                <ion-text color="medium" class="setup-hint">
                  <p>{{ setupPhase === 'first' ? 'Elige un PIN de 4 dígitos' : 'Confirma tu PIN' }}</p>
                </ion-text>

                <!-- ok-pinpad reutilizado para el alta de PIN. -->
                <div class="pinpad-wrap">
                  <ok-pinpad
                    ref="setupPinpadRef"
                    dots
                    :length="4"
                    :error="setupError"
                    @ok-complete="onSetupPinComplete"
                  ></ok-pinpad>
                </div>

                <ion-note v-if="setupError" color="danger" class="error-note">
                  Los PIN no coinciden, inténtalo de nuevo
                </ion-note>
              </div>

            </ion-card-content>
          </ion-card>

          <p class="footer-note">
            ERPlora · {{ step === 'pin' ? 'dispositivo de confianza' : 'conexión segura con Cloud' }}
          </p>

        </div>
      </div>

    </ion-content>
  </ion-page>
</template>

<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { useRouter } from 'vue-router';
import {
  IonPage, IonContent, IonCard, IonCardContent, IonButton,
  IonInput, IonInputPasswordToggle, IonCheckbox, IonText, IonSpinner, IonSegment, IonSegmentButton,
  IonLabel, IonPopover, IonNote
} from '@ionic/vue';
import HubIcon from '../components/HubIcon.vue';
import { setUser, setHubSession, getHubSession } from '../lib/session';
import { cloudLogin, setTokens, runtimeCloudSession, runtimePinLogin, runtimeSetPin } from '../lib/cloud';
import { config } from '../lib/config';
import { pinUsers } from '../lib/runtime';
import { isDark, toggleTheme } from '../lib/theme';
import { hubLogo, DEFAULT_HUB_LOGO } from '../lib/branding';

// ---------------------------------------------------------------------------
// Tipos
// ---------------------------------------------------------------------------
type Step = 'pin' | 'email' | 'setup';

interface TrustedUser {
  id: string;
  name: string;
  email?: string;
  initials: string;
}

// ---------------------------------------------------------------------------
// Tema: estado compartido (lib/theme) — mismo modo que el toggle de la topbar.
// ---------------------------------------------------------------------------
// `isDark` / `toggleTheme` se importan de lib/theme (ver imports del SFC).

// ---------------------------------------------------------------------------
// Logo de marca (lib/branding): `hubLogo` = el del hub si lo hay, si no el de ERPlora local.
// Si la URL personalizada falla (rota / offline), caemos al logo local horneado.
// ---------------------------------------------------------------------------
function onLogoError(ev: Event): void {
  const img = ev.target as HTMLImageElement;
  if (!img.src.endsWith(DEFAULT_HUB_LOGO)) img.src = DEFAULT_HUB_LOGO;
}

// ---------------------------------------------------------------------------
// Estado de la sesión de dispositivo (PIN / trust)
// PIN y lista de usuarios de confianza se persisten en localStorage bajo
// 'erplora.trusted' y 'erplora.trusted_users'. El flujo de AUTH real del
// Cloud (ARQUITECTURA.md §2.9) se implementa en cloud.ts; aquí solo leemos
// el flag y la lista para mostrar/ocultar los pasos.
// ---------------------------------------------------------------------------
function readTrusted(): boolean {
  try { return localStorage.getItem('erplora.trusted') === '1'; } catch { return false; }
}
function readTrustedUsers(): TrustedUser[] {
  try {
    const raw = localStorage.getItem('erplora.trusted_users');
    return raw ? (JSON.parse(raw) as TrustedUser[]) : [];
  } catch { return []; }
}
function saveTrustedUsers(list: TrustedUser[]): void {
  try { localStorage.setItem('erplora.trusted_users', JSON.stringify(list)); } catch { /* ignore */ }
}
function saveTrustedFlag(val: boolean): void {
  try {
    if (val) localStorage.setItem('erplora.trusted', '1');
    else localStorage.removeItem('erplora.trusted');
  } catch { /* ignore */ }
}

const trusted = ref<boolean>(readTrusted());
const trustedUsers = ref<TrustedUser[]>(readTrustedUsers());

// ---------------------------------------------------------------------------
// Flujo de pasos
// ---------------------------------------------------------------------------
const step = ref<Step>(trusted.value ? 'pin' : 'email');
const showTabs = computed(() => trusted.value && step.value !== 'setup');

// El RUNTIME (`GET /api/hub/context` → pin_users) es la AUTORIDAD de quién puede hacer login local
// por PIN. localStorage NO añade usuarios: solo **decora** con email/iniciales (hub_user no guarda
// email), cacheados del login cloud y pegados a la entrada del runtime que coincida por id. Antes se
// "conservaban" los de localStorage ausentes del runtime → podía resucitar usuarios obsoletos
// (drift); ya no. El flujo de seguridad (§2.9) NO cambia: esto solo decide qué pestaña se muestra;
// la pestaña Email sigue disponible. `immediate` cubre el caso ya resuelto.
watch(
  pinUsers,
  (users) => {
    if (!users.length || step.value === 'setup') return;
    const cachedById = new Map(trustedUsers.value.map((u) => [u.id, u]));
    trustedUsers.value = users.map((u) => ({
      id: u.id,
      name: u.name,
      initials: initials(u.name),
      email: cachedById.get(u.id)?.email,
    }));
    trusted.value = true;
    step.value = 'pin';
  },
  { immediate: true },
);

// ---------------------------------------------------------------------------
// EmailForm state
// ---------------------------------------------------------------------------
const router = useRouter();
const emailVal = ref<string>('');
const passwordVal = ref<string>('');
const trust = ref<boolean>(true);
const emailLoading = ref<boolean>(false);
const emailError = ref<string>('');

// Genera iniciales a partir del nombre completo
function initials(name: string): string {
  return name
    .trim()
    .split(/\s+/)
    .slice(0, 2)
    .map((w) => w[0]?.toUpperCase() ?? '')
    .join('');
}

async function submitEmail(): Promise<void> {
  emailError.value = '';
  emailLoading.value = true;
  try {
    // Login real contra el Cloud Portal (ARQUITECTURA.md §2.3: Bearer + X-Hub-Id).
    const result = await cloudLogin(emailVal.value.trim().toLowerCase(), passwordVal.value);
    setTokens(result.access, result.refresh);

    // Abre la sesión LOCAL del runtime a partir del JWT (autoridad de permisos local, §2.9).
    // El `name` se reusa para el login por PIN (el runtime resuelve el usuario por nombre).
    const sess = await runtimeCloudSession(result.access, result.user.name);
    setHubSession(sess.token);

    setUser({
      id: result.user.id,
      name: result.user.name,
      email: result.user.email,
      avatarUrl: result.user.avatarUrl ?? null
    });

    // Si el usuario eligió "Confiar en este dispositivo", registramos el usuario localmente y
    // vamos al alta de PIN (el PIN se fija en el runtime al confirmar — onSetupComplete).
    if (trust.value) {
      const userEntry: TrustedUser = {
        id: result.user.id,
        name: result.user.name,
        email: result.user.email,
        initials: initials(result.user.name)
      };
      const existing = trustedUsers.value.filter((u) => u.id !== result.user.id);
      trustedUsers.value = [userEntry, ...existing];
      saveTrustedUsers(trustedUsers.value);
      saveTrustedFlag(true);
      trusted.value = true;
      step.value = 'setup';
      return; // no navega aún; onSetupComplete navega tras fijar el PIN en el runtime
    }

    const redirect = (router.currentRoute.value.query.redirect as string) || '/';
    await router.replace(redirect);
  } catch {
    // Fallback demo SOLO con VITE_DEMO=1 (config.demo). En prod (sin la flag) el login falla
    // duro y mostramos el error real — nunca creamos una sesión ficticia.
    if (config.demo) {
      setUser({ id: 'u1', name: emailVal.value || 'Demo Owner', email: emailVal.value || 'demo@erplora.com' });
      if (trust.value) {
        const userEntry: TrustedUser = {
          id: 'u1',
          name: emailVal.value || 'Demo Owner',
          email: emailVal.value || 'demo@erplora.com',
          initials: initials(emailVal.value || 'Demo Owner')
        };
        trustedUsers.value = [userEntry];
        saveTrustedUsers(trustedUsers.value);
        saveTrustedFlag(true);
        trusted.value = true;
        step.value = 'setup';
        return;
      }
      const redirect = (router.currentRoute.value.query.redirect as string) || '/';
      await router.replace(redirect);
      return;
    }
    emailError.value = 'No se pudo iniciar sesión. Revisa tus credenciales o la conexión.';
  } finally {
    emailLoading.value = false;
  }
}

// ---------------------------------------------------------------------------
// PinLogin state
// ---------------------------------------------------------------------------
const pinUser = ref<TrustedUser | null>(
  trustedUsers.value.length === 1 ? trustedUsers.value[0] : null,
);
const pinValue = ref<string>('');
const pinError = ref<boolean>(false);
// Referencia al <ok-pinpad> del paso PIN (para limpiar su valor tras error / cambiar usuario).
const mainPinpadRef = ref<(HTMLElement & { value: string }) | null>(null);

function selectPinUser(u: TrustedUser): void {
  pinUser.value = u;
  pinValue.value = '';
  pinError.value = false;
}

// Eventos del ok-pinpad (el componente pinta los círculos y gestiona el teclado).
function onMainPinInput(ev: Event): void {
  pinValue.value = (ev as CustomEvent<{ value: string }>).detail.value ?? '';
  pinError.value = false;
}
function onMainPinComplete(ev: Event): void {
  const pin = (ev as CustomEvent<{ value: string }>).detail.value ?? '';
  void checkPin(pin);
}
// Tecla secundaria del pinpad (flecha atrás) → volver a elegir usuario.
function onChangeUser(): void {
  pinUser.value = null;
  pinValue.value = '';
  pinError.value = false;
  if (mainPinpadRef.value) mainPinpadRef.value.value = '';
}
// "Iniciar sesión con email" desde el paso PIN.
function onPinToEmail(): void {
  step.value = 'email';
  pinUser.value = null;
  pinValue.value = '';
  pinError.value = false;
}

async function checkPin(pin: string): Promise<void> {
  if (pin.length < 4 || !pinUser.value) return;
  try {
    // Login local por PIN contra el runtime (§2.9): verifica el PIN y abre sesión server-side.
    const u = pinUser.value;
    const sess = await runtimePinLogin(u.name, pin);
    setHubSession(sess.token);
    setUser({ id: u.id, name: u.name, email: u.email ?? '' });
    const redirect = (router.currentRoute.value.query.redirect as string) || '/';
    await router.replace(redirect);
  } catch {
    pinError.value = true;
    pinValue.value = '';
    // Limpia los círculos del ok-pinpad para reintentar.
    if (mainPinpadRef.value) mainPinpadRef.value.value = '';
  }
}

// ---------------------------------------------------------------------------
// PinSetup state
// ---------------------------------------------------------------------------
type SetupPhase = 'first' | 'confirm';
const setupPhase = ref<SetupPhase>('first');
const setupFirst = ref<string>('');
const setupError = ref<boolean>(false);
// Referencia al <ok-pinpad> del alta de PIN (para limpiar entre fases / errores).
const setupPinpadRef = ref<(HTMLElement & { value: string }) | null>(null);

function clearSetupPinpad(): void {
  if (setupPinpadRef.value) setupPinpadRef.value.value = '';
}

// Evento ok-complete del pinpad de alta: recibe el PIN completo de 4 dígitos.
function onSetupPinComplete(ev: Event): void {
  const pin = (ev as CustomEvent<{ value: string }>).detail.value ?? '';
  void onSetupComplete(pin);
}

async function onSetupComplete(pin: string): Promise<void> {
  setupError.value = false;
  if (setupPhase.value === 'first') {
    // Fase 1: guarda el primer PIN y pasa a confirmación (limpia el teclado).
    setupFirst.value = pin;
    setupPhase.value = 'confirm';
    clearSetupPinpad();
    return;
  }
  // Fase 2: confirmar contra el primero.
  if (pin === setupFirst.value) {
    // Fija el PIN en el runtime para el usuario de la sesión actual (§2.9). Requiere la sesión
    // abierta en el login cloud previo (X-Hub-Session).
    const session = getHubSession();
    try {
      if (session) await runtimeSetPin(pin, session);
      const redirect = (router.currentRoute.value.query.redirect as string) || '/';
      await router.replace(redirect);
    } catch {
      setupError.value = true;
      setupFirst.value = '';
      setupPhase.value = 'first';
      clearSetupPinpad();
    }
  } else {
    setupError.value = true;
    setupFirst.value = '';
    setupPhase.value = 'first';
    clearSetupPinpad();
  }
}
</script>

<style scoped>
/* ---- Layout ---- */
.login-wrap {
  display: grid;
  place-items: center;
  min-height: 100%;
  padding: 40px 16px;
}
.login-box {
  width: min(92vw, 400px);
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 0;
}

/* ---- Botón tema ---- */
.theme-btn {
  position: absolute;
  top: 8px;
  right: 8px;
  z-index: 10;
}

/* ---- Logo ---- */
.logo-area {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 12px;
  margin-bottom: 32px;
  text-align: center;
}
.logo-img {
  height: 56px;
  width: auto;
  max-width: 200px;
  object-fit: contain;
}
.logo-sub {
  font-size: 14px;
  color: var(--ion-color-medium);
  margin: 0;
}

/* ---- Tarjeta ---- */
.login-card {
  width: 100%;
}

/* ---- Pasos ---- */
/* Card de tamaño FIJO: todos los pasos (email / pin / setup / selección de usuario)
 * reservan la misma altura, así no hay salto al cambiar entre pestañas. El paso más
 * alto es el del teclado PIN (~411px); reservamos algo más y centramos el contenido. */
.step-form {
  display: flex;
  flex-direction: column;
  gap: 12px;
  /* Altura FIJA: misma en email / pin / setup / selección → sin salto al cambiar de paso.
   * Cabe el paso más alto (teclado PIN ~411px). El contenido se alinea arriba y, en la
   * selección de usuario, la lista scrollea dentro (ver .user-grid). */
  height: 26rem;
  /* Formulario (email / PIN / setup) CENTRADO vertical. En la selección de usuario,
   * el .user-scroll lleva flex:1 y rellena el alto, así sus cards quedan ARRIBA. */
  justify-content: center;
}

/* ---- Trust row ---- */
.trust-row {
  display: flex;
  align-items: center;
  gap: 4px;
}
.trust-label {
  font-size: 13.5px;
}
.trust-info-btn {
  margin: 0;
  height: 28px;
}

/* ---- Popover ---- */
.popover-content {
  padding: 12px;
  max-width: 260px;
}
.popover-title {
  font-weight: 600;
  margin: 0 0 4px;
  font-size: 13px;
}
.popover-body {
  font-size: 13px;
  line-height: 1.4;
  color: var(--ion-color-medium);
  margin: 0;
}

/* ---- Error note ---- */
.error-note {
  font-size: 13px;
  display: block;
}

/* ---- User grid (PIN selector) ---- */
.pin-choose-title {
  text-align: center;
}
.pin-choose-title p {
  font-size: 14px;
  margin: 0 0 8px;
}
/* Contenedor de scroll: ocupa el alto restante del card (fijo) y scrollea dentro. */
.user-scroll {
  flex: 1 1 auto;
  min-height: 0;
  overflow-y: auto;
  /* Hueco para la barra de scroll sin tapar las cards. */
  padding-right: 4px;
}
.user-grid {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: 12px;
  /* Filas a su altura natural (sin aplastar); el scroll lo hace .user-scroll. */
  align-content: start;
}
/* Cada perfil es un ion-card (button): solo reseteamos el margen para encajar en la rejilla. */
.user-card {
  margin: 0;
}
.user-card .user-name {
  margin-top: 8px;
}
.user-name {
  font-size: 14px;
  font-weight: 600;
  max-width: 100%;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  margin: 0;
}
.user-email {
  font-size: 11px;
  color: var(--ion-color-medium);
  max-width: 100%;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  margin: 2px 0 0;
}

/* ---- PIN user info ---- */
.pin-user-info {
  display: flex;
  flex-direction: column;
  align-items: center;
  text-align: center;
  gap: 4px;
}

/* ---- PinPad (wrapper del ok-pinpad: solo centra) ---- */
.pinpad-wrap {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 8px;
}

/* ---- Setup hint ---- */
.setup-hint {
  text-align: center;
}
.setup-hint p {
  font-size: 14px;
  margin: 0 0 4px;
}

/* ---- Footer note ---- */
.footer-note {
  margin-top: 24px;
  text-align: center;
  font-size: 12px;
  color: var(--ion-color-medium);
}
</style>
