// apps/web/src/pages/SystemPage.tsx
import { useState } from 'react';
import {
  IonLabel, IonCard, IonCardContent, IonList, IonItem, IonChip,
  IonButton, IonNote, IonProgressBar,
} from '@ionic/react';
import {
  LuActivity, LuCpu, LuMemoryStick, LuDatabase, LuPlugZap,
  LuMonitor, LuApple, LuTerminal, LuCircleCheck, LuRefreshCw,
  LuDatabaseBackup, LuScrollText, LuDownload,
} from 'react-icons/lu';
import type { IconType } from 'react-icons';
import { PageScaffold } from '../components/PageScaffold';
import { PagePanel } from '../components/PagePanel';
import { PageTabBar, type PageTabBarItem } from '../components/PageTabBar';
import { useToast } from '../lib/toast';

type Tab = 'resources' | 'updates' | 'backups' | 'logs';

const tabs: Array<PageTabBarItem<Tab>> = [
  { value: 'resources', label: 'Recursos', icon: <LuActivity size={22} /> },
  { value: 'updates', label: 'Actualizaciones', icon: <LuRefreshCw size={22} /> },
  { value: 'backups', label: 'Copias', icon: <LuDatabaseBackup size={22} /> },
  { value: 'logs', label: 'Registros', icon: <LuScrollText size={22} /> },
];

// Métricas de recursos del hub (demo). En producción → runtime/Cloud.
interface Metric {
  label: string;
  value: string;
  unit?: string;
  Icon: IconType;
  progress?: number;
}

const METRICS: Metric[] = [
  { label: 'RAM', value: '612 MB', unit: 'de 2 GB', Icon: LuMemoryStick, progress: 0.3 },
  { label: 'CPU', value: '0,4 cores', unit: '2 vCPU', Icon: LuCpu, progress: 0.2 },
  { label: 'Base de datos', value: '8,6 MB', unit: 'Aurora DB', Icon: LuDatabase },
  { label: 'Conexiones BD', value: '12', unit: '/ 120', Icon: LuPlugZap, progress: 0.1 },
];

const BRIDGE_OS: Array<{ label: string; Icon: IconType }> = [
  { label: 'Windows', Icon: LuMonitor },
  { label: 'macOS', Icon: LuApple },
  { label: 'Linux', Icon: LuTerminal },
];

export function SystemPage() {
  const [tab, setTab] = useState<Tab>('resources');
  const { toast } = useToast();

  return (
    <PageScaffold title="Sistema" footer={<PageTabBar value={tab} items={tabs} onChange={setTab} />}>
      {tab === 'resources' && (
        <PagePanel>
          {/* Uso de recursos */}
          <div className="erplora-kpi-grid">
            {METRICS.map((m) => (
              <IonCard key={m.label} className="settings-card ion-no-margin">
                <IonCardContent>
                  <div className="erplora-kpi">
                    <div className="erplora-kpi__top">
                      <span className="erplora-kpi__label">{m.label}</span>
                      <span className="erplora-kpi-icon"><m.Icon size={20} /></span>
                    </div>
                    <span className="erplora-kpi__value">
                      {m.value}{' '}
                      {m.unit && <small className="erplora-kpi__unit">{m.unit}</small>}
                    </span>
                    {m.progress !== undefined && (
                      <IonProgressBar value={m.progress} className="mt-2" />
                    )}
                  </div>
                </IonCardContent>
              </IonCard>
            ))}
          </div>

          {/* Conexión Bridge */}
          <IonCard className="settings-card ion-no-margin">
            <IonCardContent>
              <div className="erplora-card-header">
                <h3>Conexión Bridge</h3>
                <IonChip color="medium" className="ion-no-margin">Desconectado</IonChip>
              </div>
              <p className="erplora-muted erplora-text-sm" style={{ margin: 0 }}>
                El cliente Bridge no está corriendo en este equipo. Vincula un Bridge
                abajo para gestionar el hardware — tus impresoras, cajón y escáneres
                aparecerán aquí.
              </p>

              <ol className="erplora-steps">
                {['Descargar', 'Instalar', 'Vincular', 'Configurar'].map((s, i) => (
                  <li key={s} className="erplora-step">
                    <span className={`erplora-avatar erplora-avatar--sm${i === 0 ? '' : ' erplora-step__num--muted'}`}>
                      {i + 1}
                    </span>
                    <span className="erplora-text-sm">{s}</span>
                  </li>
                ))}
              </ol>

              <div className="erplora-bridge-download">
                <div className="erplora-feed__primary">Descargar ERPlora Bridge</div>
                <div className="erplora-feed__sub" style={{ marginBottom: 12 }}>
                  Bridge es una pequeña app nativa que conecta este hub con tus
                  impresoras, cajón y escáneres. Elige tu sistema para continuar.
                </div>
                <div className="erplora-os-grid">
                  {BRIDGE_OS.map((os) => (
                    <IonButton
                      key={os.label}
                      fill="outline"
                      onClick={() => toast(`Descargando Bridge para ${os.label}…`, { color: 'primary' })}
                    >
                      <os.Icon size={18} className="mr-2" />
                      {os.label}
                    </IonButton>
                  ))}
                </div>
              </div>
            </IonCardContent>
          </IonCard>
        </PagePanel>
      )}

      {tab === 'updates' && (
        <PagePanel bodyClassName="flex flex-col items-center gap-3 py-12 text-center">
          <span className="erplora-empty-icon erplora-empty-icon--success">
            <LuCircleCheck size={26} />
          </span>
          <strong className="text-lg">Estás al día</strong>
          <p className="erplora-muted erplora-mono m-0">Hub v3.4 · comprobado ahora</p>
          <IonButton fill="outline" onClick={() => toast('Buscando actualizaciones…', { color: 'primary' })}>
            <LuRefreshCw size={16} className="mr-2" />Buscar actualizaciones
          </IonButton>
        </PagePanel>
      )}

      {tab === 'backups' && (
        <PagePanel>
          <div className="erplora-card-header">
              <h3>Copias automáticas</h3>
              <IonButton size="small" onClick={() => toast('Creando copia…', { color: 'primary' })}>
                <LuDatabaseBackup size={16} className="mr-1" />Copia ahora
              </IonButton>
            </div>
            <div className="mb-3">
              <p className="erplora-feed__sub mb-1">Almacenamiento usado · 2,1 GB / 8 GB</p>
              <IonProgressBar value={0.26} />
            </div>
            <IonList>
              {['2026-05-30 03:00', '2026-05-29 03:00', '2026-05-28 03:00'].map((when, i, arr) => (
                <IonItem key={when} lines={i === arr.length - 1 ? 'none' : 'inset'}>
                  <span slot="start" className="text-[color:var(--ion-color-medium)]"><LuDatabase size={20} /></span>
                  <IonLabel>
                    <h2 className="font-semibold">Copia diaria</h2>
                    <IonNote className="erplora-mono">{when} · 8,6 MB</IonNote>
                  </IonLabel>
                  <IonButton slot="end" fill="clear" aria-label="Descargar">
                    <LuDownload size={18} />
                  </IonButton>
                </IonItem>
              ))}
          </IonList>
        </PagePanel>
      )}

      {tab === 'logs' && (
        <PagePanel>
          <h3 className="erplora-card-title">Registro de eventos</h3>
          <IonList>
              {[
                { when: '03:00:01', lvl: 'INFO', msg: 'backup.completed', meta: 'size=8.6MB' },
                { when: '02:14:55', lvl: 'INFO', msg: 'module.sync', meta: 'ok' },
                { when: '01:58:12', lvl: 'WARN', msg: 'bridge.disconnected', meta: 'retry=3' },
                { when: '01:40:03', lvl: 'INFO', msg: 'auth.login', meta: 'user=demo@erplora.com' },
                { when: '00:12:44', lvl: 'INFO', msg: 'invoice.issued', meta: 'INV-2026-00034' },
              ].map((l, i, arr) => (
                <IonItem key={i} lines={i === arr.length - 1 ? 'none' : 'inset'}>
                  <IonNote slot="start" className="erplora-mono w-[78px] text-[12px]">[{l.when}]</IonNote>
                  <IonChip color={l.lvl === 'WARN' ? 'warning' : 'medium'} className="ion-no-margin">{l.lvl}</IonChip>
                  <IonLabel className="ion-text-wrap erplora-mono ml-2 text-[12.5px]">
                    {l.msg} <span className="erplora-muted">{l.meta}</span>
                  </IonLabel>
                </IonItem>
              ))}
          </IonList>
        </PagePanel>
      )}
    </PageScaffold>
  );
}

// apps/web/src/views/SystemPage.vue
<template>
  <ion-page>
    <ion-header class="ion-no-border">
      <ion-toolbar>
        <ion-buttons slot="start"><ion-menu-button /></ion-buttons>
        <ion-title>Sistema</ion-title>
      </ion-toolbar>
    </ion-header>

    <ion-content class="ion-padding">

      <!-- ── Tab: Recursos ──────────────────────────────────────── -->
      <template v-if="tab === 'resources'">
        <!-- KPI grid -->
        <ion-grid class="ion-no-padding" style="margin-bottom: 16px">
          <ion-row>
            <ion-col v-for="m in METRICS" :key="m.label" size="6" size-md="3">
              <ion-card class="ion-no-margin" style="margin: 4px">
                <ion-card-content>
                  <div style="display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 4px">
                    <span style="font-size: 12px; opacity: 0.65">{{ m.label }}</span>
                    <ion-icon :icon="m.icon" style="font-size: 18px; opacity: 0.5" />
                  </div>
                  <div style="font-size: 20px; font-weight: 600; line-height: 1.2">{{ m.value }}</div>
                  <div v-if="m.unit" style="font-size: 11px; opacity: 0.55; margin-bottom: 6px">{{ m.unit }}</div>
                  <ion-progress-bar v-if="m.progress !== undefined" :value="m.progress" />
                </ion-card-content>
              </ion-card>
            </ion-col>
          </ion-row>
        </ion-grid>

        <!-- Conexión Bridge -->
        <ion-card class="ion-no-margin">
          <ion-card-content>
            <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 8px">
              <h3 style="margin: 0; font-weight: 600">Conexión Bridge</h3>
              <ion-badge color="medium">Desconectado</ion-badge>
            </div>
            <p style="margin: 0 0 12px; font-size: 13px; opacity: 0.65">
              El cliente Bridge no está corriendo en este equipo. Vincula un Bridge
              abajo para gestionar el hardware — tus impresoras, cajón y escáneres
              aparecerán aquí.
            </p>

            <ol style="margin: 0 0 16px; padding-left: 0; list-style: none; display: flex; gap: 12px; flex-wrap: wrap">
              <li v-for="(s, i) in bridgeSteps" :key="s" style="display: flex; align-items: center; gap: 6px">
                <ion-badge :color="i === 0 ? 'primary' : 'medium'" style="min-width: 22px; text-align: center">
                  {{ i + 1 }}
                </ion-badge>
                <span style="font-size: 13px">{{ s }}</span>
              </li>
            </ol>

            <div>
              <div style="font-weight: 600; margin-bottom: 4px">Descargar ERPlora Bridge</div>
              <p style="margin: 0 0 12px; font-size: 13px; opacity: 0.65">
                Bridge es una pequeña app nativa que conecta este hub con tus
                impresoras, cajón y escáneres. Elige tu sistema para continuar.
              </p>
              <div style="display: flex; gap: 8px; flex-wrap: wrap">
                <ion-button
                  v-for="os in BRIDGE_OS"
                  :key="os.label"
                  fill="outline"
                  @click="handleBridgeDownload(os.label)"
                >
                  <ion-icon slot="start" :icon="os.icon" />
                  {{ os.label }}
                </ion-button>
              </div>
            </div>
          </ion-card-content>
        </ion-card>
      </template>

      <!-- ── Tab: Actualizaciones ───────────────────────────────── -->
      <template v-else-if="tab === 'updates'">
        <ion-card class="ion-no-margin">
          <ion-card-content style="display: flex; flex-direction: column; align-items: center; gap: 12px; padding: 48px 24px; text-align: center">
            <ion-icon :icon="checkmarkCircleOutline" style="font-size: 48px; color: var(--ion-color-success)" />
            <strong style="font-size: 18px">Estás al día</strong>
            <p style="margin: 0; opacity: 0.6; font-family: monospace; font-size: 13px">Hub v3.4 · comprobado ahora</p>
            <ion-button fill="outline" @click="handleCheckUpdates">
              <ion-icon slot="start" :icon="refreshOutline" />
              Buscar actualizaciones
            </ion-button>
          </ion-card-content>
        </ion-card>
      </template>

      <!-- ── Tab: Copias ────────────────────────────────────────── -->
      <template v-else-if="tab === 'backups'">
        <ion-card class="ion-no-margin">
          <ion-card-content>
            <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 12px">
              <h3 style="margin: 0; font-weight: 600">Copias automáticas</h3>
              <ion-button size="small" @click="handleBackupNow">
                <ion-icon slot="start" :icon="cloudUploadOutline" />
                Copia ahora
              </ion-button>
            </div>
            <p style="margin: 0 0 4px; font-size: 13px; opacity: 0.65">Almacenamiento usado · 2,1 GB / 8 GB</p>
            <ion-progress-bar :value="0.26" style="margin-bottom: 16px" />
            <ion-list :inset="false">
              <ion-item
                v-for="(backup, i) in BACKUPS"
                :key="backup.when"
                :lines="i === BACKUPS.length - 1 ? 'none' : 'inset'"
              >
                <ion-icon slot="start" :icon="serverOutline" color="medium" />
                <ion-label>
                  <h2 style="font-weight: 600">Copia diaria</h2>
                  <ion-note style="font-family: monospace; font-size: 12px">{{ backup.when }} · 8,6 MB</ion-note>
                </ion-label>
                <ion-button slot="end" fill="clear" aria-label="Descargar">
                  <ion-icon slot="icon-only" :icon="downloadOutline" />
                </ion-button>
              </ion-item>
            </ion-list>
          </ion-card-content>
        </ion-card>
      </template>

      <!-- ── Tab: Registros ─────────────────────────────────────── -->
      <template v-else-if="tab === 'logs'">
        <ion-card class="ion-no-margin">
          <ion-card-content>
            <h3 style="margin: 0 0 12px; font-weight: 600">Registro de eventos</h3>
            <ion-list :inset="false">
              <ion-item
                v-for="(l, i) in LOGS"
                :key="i"
                :lines="i === LOGS.length - 1 ? 'none' : 'inset'"
              >
                <ion-note slot="start" style="font-family: monospace; font-size: 11px; width: 78px">[{{ l.when }}]</ion-note>
                <ion-badge :color="l.lvl === 'WARN' ? 'warning' : 'medium'" style="margin-right: 8px; flex-shrink: 0">
                  {{ l.lvl }}
                </ion-badge>
                <ion-label class="ion-text-wrap" style="font-family: monospace; font-size: 12.5px">
                  {{ l.msg }} <ion-note>{{ l.meta }}</ion-note>
                </ion-label>
              </ion-item>
            </ion-list>
          </ion-card-content>
        </ion-card>
      </template>

    </ion-content>

    <!-- ── Footer con ion-segment (tabs) ─────────────────────────── -->
    <ion-footer class="ion-no-border">
      <ion-toolbar>
        <ion-segment :value="tab" @ion-change="tab = ($event as CustomEvent<{ value: Tab }>).detail.value">
          <ion-segment-button value="resources">
            <ion-icon :icon="pulseOutline" />
            <ion-label>Recursos</ion-label>
          </ion-segment-button>
          <ion-segment-button value="updates">
            <ion-icon :icon="refreshOutline" />
            <ion-label>Actualizaciones</ion-label>
          </ion-segment-button>
          <ion-segment-button value="backups">
            <ion-icon :icon="cloudUploadOutline" />
            <ion-label>Copias</ion-label>
          </ion-segment-button>
          <ion-segment-button value="logs">
            <ion-icon :icon="documentTextOutline" />
            <ion-label>Registros</ion-label>
          </ion-segment-button>
        </ion-segment>
      </ion-toolbar>
    </ion-footer>

    <ion-toast
      :is-open="toastOpen"
      :message="toastMessage"
      :duration="2500"
      color="primary"
      @did-dismiss="toastOpen = false"
    />

  </ion-page>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import {
  IonPage, IonHeader, IonToolbar, IonButtons, IonMenuButton, IonTitle, IonContent,
  IonFooter, IonSegment, IonSegmentButton, IonLabel, IonCard, IonCardContent,
  IonGrid, IonRow, IonCol, IonProgressBar, IonBadge, IonIcon, IonButton,
  IonList, IonItem, IonNote, IonToast,
} from '@ionic/vue';
import {
  pulseOutline, hardwareChipOutline, serverOutline, flashOutline,
  refreshOutline, checkmarkCircleOutline, cloudUploadOutline,
  downloadOutline, documentTextOutline, desktopOutline, logoApple, terminalOutline,
} from 'ionicons/icons';

// ── Types ────────────────────────────────────────────────────────

type Tab = 'resources' | 'updates' | 'backups' | 'logs';

interface Metric {
  label: string;
  value: string;
  unit?: string;
  icon: string;
  progress?: number;
}

interface BridgeOs {
  label: string;
  icon: string;
}

interface Backup {
  when: string;
}

interface LogEntry {
  when: string;
  lvl: 'INFO' | 'WARN';
  msg: string;
  meta: string;
}

// ── State ────────────────────────────────────────────────────────

const tab = ref<Tab>('resources');
const toastMessage = ref('');
const toastOpen = ref(false);

// ── Static demo data (fiel al original) ─────────────────────────

const METRICS: Metric[] = [
  { label: 'RAM',            value: '612 MB',   unit: 'de 2 GB',  icon: serverOutline,       progress: 0.3  },
  { label: 'CPU',            value: '0,4 cores', unit: '2 vCPU',  icon: hardwareChipOutline, progress: 0.2  },
  { label: 'Base de datos',  value: '8,6 MB',   unit: 'Aurora DB', icon: serverOutline                     },
  { label: 'Conexiones BD',  value: '12',       unit: '/ 120',    icon: flashOutline,         progress: 0.1 },
];

const bridgeSteps: string[] = ['Descargar', 'Instalar', 'Vincular', 'Configurar'];

const BRIDGE_OS: BridgeOs[] = [
  { label: 'Windows', icon: desktopOutline },
  { label: 'macOS',   icon: logoApple      },
  { label: 'Linux',   icon: terminalOutline },
];

const BACKUPS: Backup[] = [
  { when: '2026-05-30 03:00' },
  { when: '2026-05-29 03:00' },
  { when: '2026-05-28 03:00' },
];

const LOGS: LogEntry[] = [
  { when: '03:00:01', lvl: 'INFO', msg: 'backup.completed',   meta: 'size=8.6MB'              },
  { when: '02:14:55', lvl: 'INFO', msg: 'module.sync',        meta: 'ok'                       },
  { when: '01:58:12', lvl: 'WARN', msg: 'bridge.disconnected', meta: 'retry=3'                 },
  { when: '01:40:03', lvl: 'INFO', msg: 'auth.login',         meta: 'user=demo@erplora.com'    },
  { when: '00:12:44', lvl: 'INFO', msg: 'invoice.issued',     meta: 'INV-2026-00034'           },
];

// ── Handlers ─────────────────────────────────────────────────────

function showToast(message: string): void {
  toastMessage.value = message;
  toastOpen.value = true;
}

function handleBridgeDownload(os: string): void {
  showToast(`Descargando Bridge para ${os}…`);
}

function handleCheckUpdates(): void {
  showToast('Buscando actualizaciones…');
}

function handleBackupNow(): void {
  showToast('Creando copia…');
}
</script>
