// apps/web/src/views/BillingPage.vue
<template>
  <ion-page>
    <ion-header class="ion-no-border">
      <ion-toolbar>
        <ion-buttons slot="start">
          <ion-menu-button />
        </ion-buttons>
        <ion-title>Billing</ion-title>
      </ion-toolbar>
    </ion-header>

    <ion-content class="ion-padding">
      <!-- Facturas -->
      <template v-if="tab === 'invoices'">
        <h2 class="text-lg font-semibold mb-3">Facturas</h2>

        <div v-if="loadingInvoices" class="flex justify-center py-10">
          <ion-spinner name="dots" />
        </div>

        <template v-else-if="invoices.length > 0">
          <!-- Tabla (pantallas medianas+) -->
          <div class="hidden sm:block overflow-x-auto">
            <table class="w-full text-sm">
              <thead>
                <tr class="border-b border-[color:var(--ion-border-color)]">
                  <th class="text-left py-2 px-3 font-medium opacity-60">Factura</th>
                  <th class="text-left py-2 px-3 font-medium opacity-60">Fecha</th>
                  <th class="text-left py-2 px-3 font-medium opacity-60">Vencimiento</th>
                  <th class="text-right py-2 px-3 font-medium opacity-60">Importe</th>
                  <th class="text-left py-2 px-3 font-medium opacity-60">Estado</th>
                  <th class="py-2 px-3"></th>
                </tr>
              </thead>
              <tbody>
                <tr
                  v-for="inv in invoices"
                  :key="inv.id"
                  class="border-b border-[color:var(--ion-border-color)] last:border-0"
                >
                  <td class="py-2 px-3">{{ inv.number }}</td>
                  <td class="py-2 px-3">{{ fmtDate(inv.issueDate) }}</td>
                  <td class="py-2 px-3">{{ fmtDate(inv.dueDate) }}</td>
                  <td class="py-2 px-3 text-right font-medium">{{ fmtMoney(inv.total, inv.currency) }}</td>
                  <td class="py-2 px-3">
                    <ion-badge :color="statusColor(inv.status)">{{ statusLabel(inv.status) }}</ion-badge>
                  </td>
                  <td class="py-2 px-3 text-right">
                    <ion-button fill="clear" size="small" :aria-label="`Descargar ${inv.number}`" @click="downloadInvoice(inv.id)">
                      <ion-icon slot="icon-only" :icon="downloadOutline" />
                    </ion-button>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>

          <!-- Tarjetas (móvil) -->
          <div class="flex flex-col gap-3 sm:hidden">
            <ion-card v-for="inv in invoices" :key="inv.id">
              <ion-card-header>
                <ion-card-title class="flex items-center gap-2 text-base">
                  <ion-icon :icon="documentTextOutline" class="text-[color:var(--ion-color-medium)]" />
                  {{ inv.number }}
                </ion-card-title>
              </ion-card-header>
              <ion-card-content>
                <div class="flex items-center justify-between mb-2">
                  <span class="font-semibold">{{ fmtMoney(inv.total, inv.currency) }}</span>
                  <ion-badge :color="statusColor(inv.status)">{{ statusLabel(inv.status) }}</ion-badge>
                </div>
                <p class="text-xs opacity-60">
                  Emitida {{ fmtDate(inv.issueDate) }} · Vence {{ fmtDate(inv.dueDate) }}
                </p>
                <ion-button fill="clear" size="small" class="mt-2 -ml-2" @click="downloadInvoice(inv.id)">
                  <ion-icon slot="start" :icon="downloadOutline" />
                  Descargar
                </ion-button>
              </ion-card-content>
            </ion-card>
          </div>
        </template>

        <div v-else class="flex flex-col items-center justify-center py-16 gap-2 opacity-50">
          <ion-icon :icon="receiptOutline" style="font-size: 2.5rem;" />
          <p>No hay facturas</p>
        </div>
      </template>

      <!-- Suscripciones -->
      <template v-else-if="tab === 'subscriptions'">
        <h2 class="text-lg font-semibold mb-3">Suscripciones</h2>

        <div v-if="loadingSubs" class="flex justify-center py-10">
          <ion-spinner name="dots" />
        </div>

        <template v-else-if="subscriptions.length > 0">
          <!-- Tabla (pantallas medianas+) -->
          <div class="hidden sm:block overflow-x-auto">
            <table class="w-full text-sm">
              <thead>
                <tr class="border-b border-[color:var(--ion-border-color)]">
                  <th class="text-left py-2 px-3 font-medium opacity-60">Suscripción</th>
                  <th class="text-right py-2 px-3 font-medium opacity-60">Precio</th>
                  <th class="text-left py-2 px-3 font-medium opacity-60">Renueva</th>
                  <th class="text-left py-2 px-3 font-medium opacity-60">Estado</th>
                </tr>
              </thead>
              <tbody>
                <tr
                  v-for="sub in subscriptions"
                  :key="sub.id"
                  class="border-b border-[color:var(--ion-border-color)] last:border-0"
                >
                  <td class="py-2 px-3">{{ sub.planName }}</td>
                  <td class="py-2 px-3 text-right font-medium">
                    {{ fmtMoney(sub.planPrice, 'EUR') }}/{{ sub.billingCycle || 'mes' }}
                  </td>
                  <td class="py-2 px-3">{{ fmtDate(sub.currentPeriodEnd ?? '') }}</td>
                  <td class="py-2 px-3">
                    <ion-badge :color="statusColor(sub.status)">{{ statusLabel(sub.status) }}</ion-badge>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>

          <!-- Tarjetas (móvil) -->
          <div class="flex flex-col gap-3 sm:hidden">
            <ion-card v-for="sub in subscriptions" :key="sub.id">
              <ion-card-header>
                <ion-card-title class="flex items-center gap-2 text-base">
                  <ion-icon :icon="cardOutline" class="text-[color:var(--ion-color-medium)]" />
                  {{ sub.planName }}
                </ion-card-title>
              </ion-card-header>
              <ion-card-content>
                <p class="font-semibold mb-1">
                  {{ fmtMoney(sub.planPrice, 'EUR') }}/{{ sub.billingCycle || 'mes' }}
                </p>
                <ion-badge :color="statusColor(sub.status)">{{ statusLabel(sub.status) }}</ion-badge>
                <p v-if="sub.currentPeriodEnd" class="text-xs opacity-60 mt-2">
                  {{ sub.cancelAtPeriodEnd ? 'Finaliza' : 'Renueva' }} {{ fmtDate(sub.currentPeriodEnd) }}
                </p>
              </ion-card-content>
            </ion-card>
          </div>
        </template>

        <div v-else class="flex flex-col items-center justify-center py-16 gap-2 opacity-50">
          <ion-icon :icon="refreshOutline" style="font-size: 2.5rem;" />
          <p>No hay suscripciones activas</p>
        </div>
      </template>

      <!-- Pagos -->
      <template v-else>
        <div class="flex items-center justify-center py-16 text-center opacity-60">
          <p>La gestión del método de pago se realiza desde el portal de facturación.</p>
        </div>
      </template>
    </ion-content>

    <!-- Tabs en footer -->
    <ion-footer class="ion-no-border">
      <ion-toolbar>
        <ion-segment :value="tab" @ion-change="onTabChange">
          <ion-segment-button value="invoices">
            <ion-icon :icon="receiptOutline" />
            <ion-label>Facturas</ion-label>
          </ion-segment-button>
          <ion-segment-button value="subscriptions">
            <ion-icon :icon="refreshOutline" />
            <ion-label>Suscripciones</ion-label>
          </ion-segment-button>
          <ion-segment-button value="payments">
            <ion-icon :icon="cardOutline" />
            <ion-label>Pagos</ion-label>
          </ion-segment-button>
        </ion-segment>
      </ion-toolbar>
    </ion-footer>
  </ion-page>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import {
  IonPage, IonHeader, IonToolbar, IonButtons, IonMenuButton, IonTitle, IonContent,
  IonFooter, IonSegment, IonSegmentButton, IonLabel, IonIcon, IonBadge,
  IonButton, IonCard, IonCardHeader, IonCardTitle, IonCardContent, IonSpinner,
} from '@ionic/vue';
import {
  receiptOutline, refreshOutline, cardOutline, downloadOutline, documentTextOutline,
} from 'ionicons/icons';
import {
  cloudInvoices, cloudSubscriptions, getAccessToken,
  type CloudInvoice, type CloudSubscription,
} from '../lib/cloud';
import { config } from '../lib/config';

type BillingTab = 'invoices' | 'subscriptions' | 'payments';

const tab = ref<BillingTab>('invoices');
const invoices = ref<CloudInvoice[]>([]);
const subscriptions = ref<CloudSubscription[]>([]);
const loadingInvoices = ref(true);
const loadingSubs = ref(true);

// --- Handlers ---
function onTabChange(ev: Event): void {
  const detail = (ev as CustomEvent<{ value: string }>).detail;
  if (detail.value === 'invoices' || detail.value === 'subscriptions' || detail.value === 'payments') {
    tab.value = detail.value;
  }
}

// --- Formatters ---
function fmtDate(iso: string): string {
  if (!iso) return '—';
  return new Date(iso).toLocaleDateString('es-ES', { day: '2-digit', month: 'short', year: 'numeric' });
}

function fmtMoney(n: number, currency: string): string {
  return new Intl.NumberFormat('es-ES', { style: 'currency', currency: currency || 'EUR' }).format(n);
}

// Estado → etiqueta / color Ionic
const STATUS_LABEL: Record<CloudInvoice['status'], string> = {
  draft: 'Borrador',
  open: 'Abierta',
  paid: 'Pagada',
  void: 'Anulada',
  uncollectible: 'Incobrable',
};

const STATUS_COLOR: Record<CloudInvoice['status'], string> = {
  draft: 'medium',
  open: 'warning',
  paid: 'success',
  void: 'medium',
  uncollectible: 'danger',
};

function statusLabel(s: CloudInvoice['status']): string {
  return STATUS_LABEL[s] ?? s;
}

function statusColor(s: CloudInvoice['status']): string {
  return STATUS_COLOR[s] ?? 'medium';
}

// --- Fetch al montar ---
onMounted(() => {
  cloudInvoices()
    .then((data) => { invoices.value = data; })
    .catch(() => { invoices.value = []; })
    .finally(() => { loadingInvoices.value = false; });

  cloudSubscriptions()
    .then((data) => { subscriptions.value = data; })
    .catch(() => { subscriptions.value = []; })
    .finally(() => { loadingSubs.value = false; });
});

// --- Descarga PDF de factura (endpoint real del Cloud) ---
async function downloadInvoice(id: number): Promise<void> {
  const token = getAccessToken();
  try {
    const res = await fetch(`${config.cloudApiUrl}/api/v1/billing/invoices/${id}/download/`, {
      headers: {
        ...(token ? { Authorization: `Bearer ${token}` } : {}),
        'X-Client-Type': 'hub',
      },
    });
    if (!res.ok) throw new Error(String(res.status));
    const blob = await res.blob();
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `factura-${id}.pdf`;
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
  } catch (e) {
    console.error('No se pudo descargar la factura', e);
  }
}
</script>

// apps/web/src/pages/BillingPage.tsx
import { useEffect, useState } from 'react';
import { IonButton, IonIcon } from '@ionic/react';
import { receiptOutline, refreshOutline, cardOutline } from 'ionicons/icons';
import { LuDownload, LuFileText, LuCreditCard } from 'react-icons/lu';
import { PageScaffold } from '../components/PageScaffold';
import { PageTabBar, type PageTabBarItem } from '../components/PageTabBar';
import { DataTable, type DataTableColumn } from '../components/DataTable';
import { Badge, type BadgeTone } from '../components/Badge';
import { config } from '../lib/config';
import {
  cloudInvoices, cloudSubscriptions, getAccessToken,
  type CloudInvoice, type CloudSubscription,
} from '../lib/cloud';

type BillingTab = 'invoices' | 'subscriptions' | 'payments';

const tabs: Array<PageTabBarItem<BillingTab>> = [
  { value: 'invoices', label: 'Facturas', icon: <IonIcon icon={receiptOutline} /> },
  { value: 'subscriptions', label: 'Suscripciones', icon: <IonIcon icon={refreshOutline} /> },
  { value: 'payments', label: 'Pagos', icon: <IonIcon icon={cardOutline} /> },
];

const fmtDate = (iso: string) =>
  iso ? new Date(iso).toLocaleDateString('es-ES', { day: '2-digit', month: 'short', year: 'numeric' }) : '—';
const fmtMoney = (n: number, currency: string) =>
  new Intl.NumberFormat('es-ES', { style: 'currency', currency: currency || 'EUR' }).format(n);

// Estado de factura/suscripción del Cloud (StatusD51Enum) → etiqueta + tono.
const STATUS_LABEL: Record<CloudInvoice['status'], string> = {
  draft: 'Borrador', open: 'Abierta', paid: 'Pagada', void: 'Anulada', uncollectible: 'Incobrable',
};
const STATUS_TONE: Record<CloudInvoice['status'], BadgeTone> = {
  draft: 'neutral', open: 'warning', paid: 'success', void: 'neutral', uncollectible: 'danger',
};

export function BillingPage() {
  const [tab, setTab] = useState<BillingTab>('invoices');
  const [invoices, setInvoices] = useState<CloudInvoice[]>([]);
  const [subscriptions, setSubscriptions] = useState<CloudSubscription[]>([]);
  const [loadingInvoices, setLoadingInvoices] = useState(true);
  const [loadingSubs, setLoadingSubs] = useState(true);

  useEffect(() => {
    let cancelled = false;
    cloudInvoices()
      .then((data) => { if (!cancelled) setInvoices(data); })
      .catch(() => { if (!cancelled) setInvoices([]); })
      .finally(() => { if (!cancelled) setLoadingInvoices(false); });
    cloudSubscriptions()
      .then((data) => { if (!cancelled) setSubscriptions(data); })
      .catch(() => { if (!cancelled) setSubscriptions([]); })
      .finally(() => { if (!cancelled) setLoadingSubs(false); });
    return () => { cancelled = true; };
  }, []);

  const invoiceColumns: Array<DataTableColumn<CloudInvoice>> = [
    { key: 'number', header: 'Factura', width: 'minmax(10rem,1fr)' },
    { key: 'issueDate', header: 'Fecha', filter: 'dateRange', width: '8.5rem', cell: (r) => fmtDate(r.issueDate) },
    { key: 'dueDate', header: 'Vencimiento', filter: 'dateRange', width: '9rem', cell: (r) => fmtDate(r.dueDate) },
    { key: 'total', header: 'Importe', align: 'end', width: '8rem', cell: (r) => fmtMoney(r.total, r.currency) },
    {
      key: 'status', header: 'Estado', filter: 'select', width: '9rem',
      value: (r) => STATUS_LABEL[r.status],
      cell: (r) => <Badge tone={STATUS_TONE[r.status]}>{STATUS_LABEL[r.status]}</Badge>,
    },
  ];

  const subColumns: Array<DataTableColumn<CloudSubscription>> = [
    { key: 'planName', header: 'Suscripción', width: 'minmax(12rem,1.5fr)' },
    { key: 'planPrice', header: 'Precio', align: 'end', width: '9rem', cell: (r) => `${fmtMoney(r.planPrice, 'EUR')}/${r.billingCycle || 'mes'}` },
    { key: 'currentPeriodEnd', header: 'Renueva', filter: 'dateRange', width: '9rem', cell: (r) => fmtDate(r.currentPeriodEnd ?? '') },
    {
      key: 'status', header: 'Estado', filter: 'select', width: '9rem',
      value: (r) => STATUS_LABEL[r.status],
      cell: (r) => <Badge tone={STATUS_TONE[r.status]}>{STATUS_LABEL[r.status]}</Badge>,
    },
  ];

  return (
    <PageScaffold title="Billing" footer={<PageTabBar value={tab} items={tabs} onChange={setTab} />}>
      <div className="flex h-full flex-col">
        {tab === 'invoices' && (
          <DataTable
            columns={invoiceColumns}
            rows={invoices}
            rowKey={(r) => String(r.id)}
            title="Facturas"
            loading={loadingInvoices}
            pageSize={12}
            enableExport
            exportFilename="facturas"
            emptyMessage="No hay facturas"
            rowActions={(r) => (
              <IonButton fill="clear" size="small" aria-label={`Descargar ${r.number}`} onClick={() => downloadInvoice(r.id)}>
                <LuDownload size={17} />
              </IonButton>
            )}
            cardIcon={() => <LuFileText size={18} />}
            cardTitle={(r) => r.number}
            renderCard={(r) => (
              <div className="flex flex-col gap-2 p-4">
                <div className="flex items-center justify-between">
                  <span className="font-semibold">{fmtMoney(r.total, r.currency)}</span>
                  <Badge tone={STATUS_TONE[r.status]}>{STATUS_LABEL[r.status]}</Badge>
                </div>
                <span className="text-xs text-[color:var(--ion-color-medium)]">Emitida {fmtDate(r.issueDate)} · Vence {fmtDate(r.dueDate)}</span>
              </div>
            )}
          />
        )}

        {tab === 'subscriptions' && (
          <DataTable
            columns={subColumns}
            rows={subscriptions}
            rowKey={(r) => String(r.id)}
            title="Suscripciones"
            loading={loadingSubs}
            emptyMessage="No hay suscripciones activas"
            cardIcon={() => <LuCreditCard size={18} />}
            cardTitle={(r) => r.planName}
            renderCard={(r) => (
              <div className="flex flex-col gap-2 p-4">
                <span className="font-semibold">{fmtMoney(r.planPrice, 'EUR')}/{r.billingCycle || 'mes'}</span>
                <Badge tone={STATUS_TONE[r.status]}>{STATUS_LABEL[r.status]}</Badge>
                {r.currentPeriodEnd && (
                  <span className="text-xs text-[color:var(--ion-color-medium)]">
                    {r.cancelAtPeriodEnd ? 'Finaliza' : 'Renueva'} {fmtDate(r.currentPeriodEnd)}
                  </span>
                )}
              </div>
            )}
          />
        )}

        {tab === 'payments' && (
          <div className="grid flex-1 place-items-center text-center text-[color:var(--ion-color-medium)]">
            La gestión del método de pago se realiza desde el portal de facturación.
          </div>
        )}
      </div>
    </PageScaffold>
  );
}

// Descarga del PDF de la factura (endpoint real del Cloud).
async function downloadInvoice(id: number) {
  const token = getAccessToken();
  try {
    const res = await fetch(`${config.cloudApiUrl}/api/v1/billing/invoices/${id}/download/`, {
      headers: { ...(token ? { Authorization: `Bearer ${token}` } : {}), 'X-Client-Type': 'hub-next' },
    });
    if (!res.ok) throw new Error(String(res.status));
    const blob = await res.blob();
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = `factura-${id}.pdf`;
    document.body.appendChild(a); a.click(); a.remove();
    URL.revokeObjectURL(url);
  } catch (e) {
    console.error('No se pudo descargar la factura', e);
  }
}

export default BillingPage;
